### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку  linked_lists  Чаркин Константин

### ISSUE THREAD

**Issue by kostya93** [kostya93/au-linux-kernel-spring-2016#1]
https://github.com/kostya93/au-linux-kernel-spring-2016/commit/93709e40a3eaca4d08bddced2595e19682eb270d

**Comment by eabatalov** [comment]
Many mistakes see comments in commit.
1.5 points out of 5.

**Comment by eabatalov** [comment]
Need to make you mark higher to get more consistent result with others.
2.5 out of 5 points.
